name: temperature_tracker
description: An app to monitor your own temperature.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  flutter_launcher_name: "^0.0.1"
  intl: ^0.16.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_launcher_name:
  name: "Temperature Tracker"

flutter:

  uses-material-design: true